### PR TITLE
fix:changing regex to allow 0 in the queryID

### PR DESCRIPTION
**Pull request by matthewbond**
The regex for query id will not match query ids which contain a 0:

https://regex101.com/r/dVJKLw/1

Screenshot 2021-08-31 at 18 18 11

I think we need to change the regex to allow a 0:

https://regex101.com/r/40yYZX/1

Screenshot 2021-08-31 at 18 18 02

### CODE REVIEW

**Comment by rayrutjes** [comment]
Does it or should we allow capital letters?

**Comment by matthewbond** [comment]
@rayrutjes From what I can see [here](https://www.algolia.com/doc/api-reference/api-methods/clicked-object-ids-after-search/#method-param-queryid) the queryID does not contain capital letters, I did some test searches and indeed the letters were all lowercase.

**Comment by rayrutjes** [comment]
Indeed and it's properly documented in lowercase!

**Review by rayrutjes — APPROVED** [review]

**Review by tkrugg — APPROVED** [review]

**Comment by matthewbond** [comment]
thanks @rayrutjes and @tkrugg !

**Pull request merged**
