### PR TITLE
feat: add value+currency support for conversion events

### PR DESCRIPTION
**Pull request by jonathaningram**
EEX-780

### CODE REVIEW

**Comment by jonathaningram** [comment]
New fields:

image
image
image

Nothing for view events though:

image

Event works in real test:

image

**Review by JasonBerry — APPROVED** [review]
Just want to confirm that these are all optional, right? They can be left empty? I just want to ensure our customers aren't going to have any rejected events or similar?

**Comment by jonathaningram** [comment]
> Just want to confirm that these are all optional, right? They can be left empty? I just want to ensure our customers aren't going to have any rejected events or similar?

This is a great call out.

Will check the fields in this PR. But, a quick check of my previous PR and I see that we now force a subtype but we need a "none" option for the previous cases. Will fix that.

image

**Comment by jonathaningram** [comment]
Lone conversion event with no currency/value set:

image

Observe that currency/value not provided in payload and event succeeds:

image

**Review by JasonBerry — APPROVED** [review]

**Pull request merged**
